### ISSUE TITLE
Should modifier be a module or a file ?

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#13]
Currently modifiers are modules, so they must be in `PYTHONPATH`. As modifiers locations are naturally bound to test definition it means that the `PYTHONPATH` must be changed for each test definition.

I wonder if modifier should be python file (executed with `exec(open(filename).read())`) instead of modules.

**Comment by jm-cc** [comment]
I would store the modifier related to a a test definition inside the gcvb instance (like in https://github.com/jm-cc/gcvb-examples/tree/master/getting_started for custom_scripts/modifier_example.py).

Initially gcvb command had to be launched from the gcvb root directory (where the config.yaml file is located) and therefore the gcvb root directory was in *sys.path*.

Now, it is possible to invoke gcvb in a subdirectory  of a gcvb instance which cause problems when a modifier is needed. (launching the dashboard from the *results* directory for instance).

Since "a program is allowed to modify [sys.path] for its own purpose" (https://docs.python.org/3.8/library/sys.html#sys.path), I think adding the gcvb instance root to sys.path is a raisonable fix.

Do you have something else in mind ?

**Comment by jeromerobert** [comment]
> I think adding the gcvb instance root to sys.path is a raisonable fix.

That sounds good.

> Do you have something else in mind ?

Nothing better that what you suggest.
