### ISSUE TITLE
Reading test.yaml is slow

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#17]
Reading YAML in python is slow. That's a [known issue](https://stackoverflow.com/questions/27743711/can-i-speedup-yaml) and there is not that much that you can do. `test.yaml` is read (at least) when dashboard is started and when running `generate` (which happen each time the modifier file is changed). That is, quite often.

Would it be possible to add a cache (ex: a pickle cache) for the test.yaml so it's only reread when modified ?

**Comment by jm-cc** [comment]
I am thinking of a db pickle cache who could allow to store every different version of the yaml. 
Basically computing a hash of a yaml and if it exists in db, load the pickle instead of the file.

This way every old computations could be analyse "as it was" and not as the current yaml is. But is it what the user trully wants ? Don't he prefer to check the old computations with the current treshold and references ?

There is also the problem of the modifier that can change over time, resulting in an inconsistancy between what was and what we look. 

Anyway, the cache can exists before that question has been resolved.

**Comment by jm-cc** [comment]
pickle cache is now a reality since v 0.0.2.
